server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://47.113.178.219:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Zbr14222.
#    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 10
      keepalive-time: 8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  redis:
    host: 47.113.178.219
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 5
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100
    timeout: 30000ms
  elasticsearch:
    rest:
      uris: http://150.158.144.48:9200
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: LTAI5tQ5YW4xXy2RC5nDaYZv
  secretKey: yzt34ICFqAxND6pMPCaJOHEq9giz1l
  bucket: zbr1231
baidu:
  appId: 28921867
  apiKey: l1XPwUMaZf1DhbQmci71yDHr
  secretKey: IpzMwVuxmxe4celtikNhGCaedesUWWvD