server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 300
      max-lifetime: 6
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 47.92.105.164
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 5
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100
    timeout: 30000ms
  profiles:
    active: dev
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto


oss:
  accessKey: LTAI5tQ5YW4xXy2RC5nDaYZv
  secretKey: yzt34ICFqAxND6pMPCaJOHEq9giz1l
  bucket: zbr1231