spring:
  datasource:
    url: jdbc:mysql://139.9.113.118:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Zbr14222.
  redis:
    host: 47.113.178.219
    port: 6379